name: main

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install packages
        run: pnpm install
      - name: Build extension
        run: pnpm build
      - name: Create CRX package
        run: |
          chrome_version=$(google-chrome-stable --version)
          echo "Creating CRX package with $chrome_version"
          google-chrome-stable --no-message-box --pack-extension=$(pwd)/dist
          stat ./dist.crx ./dist.pem
      - name: Save extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: |
            ./dist.crx
            ./dist.pem
